### ISSUE TITLE
Cannot load ACP after upgrading NodeBB version

### ISSUE THREAD

**Issue by orweinberger** [NicolasSiver/nodebb-plugin-ns-custom-fields#13]
Looks like ns-custom-fields is causing some issues after upgrading: https://github.com/NodeBB/NodeBB/issues/5756#issuecomment-309311112

**Comment by NicolasSiver** [comment]
The plugin prevents a minification process for ACP scripts.

**Comment by NicolasSiver** [comment]
Ok. After some investigation, I have discovered that there is an issue with plugin's `acp.js` script.
When I have excluded script from minification, NodeBB ACP builds correctly...
