### ISSUE TITLE
Can't access to "Change Extra" section in Profile

### ISSUE THREAD

**Issue by AngellitoX** [NicolasSiver/nodebb-plugin-ns-custom-fields#15]
Hello! I'm running NodeBB 1.5.2 and Custom Fields 5.0.0.

I have successfully added the  into profile.tpl, but, when I go to "Edit" in my Profile and click on Change Extra, it returns to a non-existent page. In addition, it adds a "dot" between the NodeBB url and the custom-fields link:

`https://walkingplayers.com/foro./edit/custom-fields`

My Forum is https://walkingplayers.com/foro

How could I fix this?

In advance, thank you so much!

**Comment by NicolasSiver** [comment]
There are multiple templates, which of them did you integrate?

**Comment by AngellitoX** [comment]
Sorry for the late reply! I was adding the Flex Version into the persona Theme using this:



The issue is that I can't see anything and the "Change Extra" buttom leads to "./edit/custom-fields" with that weird dot at the beginning.

**Comment by NicolasSiver** [comment]
I see an issue. The current implementation does not work well with forums which are hosted under the path. Like in your case you are hosting a forum at `foro`. I will look what could be done.

**Comment by AngellitoX** [comment]
Thank you so much! Happy to have pointed a bug :D
