### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by DDril** [NicolasSiver/nodebb-plugin-ns-custom-fields#18]
Good morning,

I have an error in the admin of this plugin.

Erreur Interne.
Oops ! Il semblerait que quelque chose se soit mal passé !
/admin/plugins/custom-fields
Failed to lookup view "admin/plugins/custom-fields" in views directory "/var/www/webapps/ddril/prison/build/public/templates"

I have the version 1.6.1 of NodeBB
Thanks in advance for your support.

**Comment by NicolasSiver** [comment]
Did you use plugin before `1.6.1` or you are using the plugin for the first time?

**Comment by DDril** [comment]
For the fist time and tanks for the answer

**Comment by NicolasSiver** [comment]
Try to stop forum, build templates and run it again:

```
./nodebb stop
./nodebb build
./nodebb start
```

Does it help?

**Comment by DDril** [comment]
It's ok.
I had uninstall the vanilla theme, I just put it back.
Thank for the support
