### ISSUE TITLE
Field input types

### ISSUE THREAD

**Issue by Radiergummi** [NicolasSiver/nodebb-plugin-ns-custom-fields#2]
Multiple data representation methods would be great: For example checkboxes/radio buttons, text areas and text fields, selects etc.

**Comment by NicolasSiver** [comment]
Comboboxes and TextAreas will be the fist one input types.

Could you provide example for checkbox user field? ;) I think checkbox could be represented as combobox, with 2 options, and radio buttons as combobox with several options ;)

**Comment by Radiergummi** [comment]
Well, I thought of things like  
- [x] I am an active plugin developer
- [ ] I like JS
- [x] I like PHP


But you are probably right, that's a cleaner approach :)
