### ISSUE TITLE
How to create custom fields programatically while creating new user through API?

### ISSUE THREAD

**Issue by mudivili** [NicolasSiver/nodebb-plugin-ns-custom-fields#20]
Hey, we create new user automatically using API. We like to add custom fields, while doing so. 
With this plugin, I am able to add new custom fields from profile page. How do I do the same while creating user? 

Basically, I like to do something like this:

```
User.create({username: '...', email: '...', fullname: '...', customField: '...'})
```
and be able to edit that field using `nodebb-plugin-ns-custom-fields` plugin.

is that possible? 

Thank you!

**Comment by NicolasSiver** [comment]
Hello. There is no explicit API to set a custom field. But you can directly put a record in a database, but there is no guarantee that this approach will work with future updates to the plugin if any.
