### ISSUE TITLE
How can I remove "Change Extra" field added at profile after uninstall?

### ISSUE THREAD

**Issue by cmcimport** [NicolasSiver/nodebb-plugin-ns-custom-fields#24]
Hi, I installed your plugin and it added a "Change Extra" at profile.
I want to know how to remove this link, how can I do it?
Also I want to know how to rename '^^
Sorry for the basic questions, I'm freshman in nodebb and nodejs
![01](https://user-images.githubusercontent.com/12444305/45581863-541bf380-b8a6-11e8-9d13-79867244e77c.PNG)

**Comment by NicolasSiver** [comment]
Rebuild of templates should help. Regards.
