### ISSUE TITLE
Support for Write API

### ISSUE THREAD

**Issue by Joykiller** [NicolasSiver/nodebb-plugin-ns-custom-fields#27]
Would be awesome for write API support.

Much like this plugin has done: https://github.com/NodeBB/nodebb-plugin-friends

**Comment by NicolasSiver** [comment]
I think it's an interesting idea overall to have API for the plugins, but it makes them a bit more complex and it makes maintenance even harder. 

This plugin was designed to be used via ACP. Where you can add/remove fields. It's unlikely that support for external HTTP API will be added.
