### ISSUE TITLE
Profile fields are not visible on profile edit page

### ISSUE THREAD

**Issue by Radiergummi** [NicolasSiver/nodebb-plugin-ns-custom-fields#4]
Seems like this conflicts with a recent nodebb update, unfortunately I cannot tell which because my users just told me today it was no longer working. Any idea? I have the following error in the dev console, don't know if its related or not:  
```
Uncaught TypeError: c[a.type] is not a function
  o @ nodebb.min.js?bf90aa35:21
  s @ nodebb.min.js?bf90aa35:21
  (anonymous function) @ nodebb.min.js?bf90aa35:21
  d.onack @ nodebb.min.js?bf90aa35:8
  d.onpacket @ nodebb.min.js?bf90aa35:8
  (anonymous function) @ nodebb.min.js?bf90aa35:8
  n.emit @ nodebb.min.js?bf90aa35:8
  h.ondecoded @ nodebb.min.js?bf90aa35:8
  (anonymous function) @ nodebb.min.js?bf90aa35:8
  n.emit @ nodebb.min.js?bf90aa35:8
  d.add @ nodebb.min.js?bf90aa35:10
  h.ondata @ nodebb.min.js?bf90aa35:8
  (anonymous function) @ nodebb.min.js?bf90aa35:8
  n.emit @ nodebb.min.js?bf90aa35:8
  d.onPacket @ nodebb.min.js?bf90aa35:8
  (anonymous function) @ nodebb.min.js?bf90aa35:8
  n.emit @ nodebb.min.js?bf90aa35:8
  o.onPacket @ nodebb.min.js?bf90aa35:9
  o.onData @ nodebb.min.js?bf90aa35:9
  ws.onmessage @ nodebb.min.js?bf90aa35:9
```

**Comment by NicolasSiver** [comment]
What exactly doesn't working?
Which update to NodeBB?

**Comment by Radiergummi** [comment]
![bildschirmfoto 2015-06-29 um 08 14 41](https://cloud.githubusercontent.com/assets/6115429/8401989/eba6a564-1e36-11e5-8406-dce90c67d0c4.png)

I am lacking the input fields to edit the profile fields. NodeBB is on 3e386e7668.

**Comment by NicolasSiver** [comment]
And what do you have before update to the latest commit?
https://github.com/NodeBB/NodeBB/commits/v0.7.x

If it have worked before update, problem is in integration with forum.
Did you update Persona Theme?

**Comment by Radiergummi** [comment]
Unfortunately I don't know which version I had before, but it didn't work before, either. I did the last `git pull` a few weeks ago and yesterday some users reported they couldn't modify their profile fields. Now to see if it helps, I pulled again today, but no luck with that.

I don't use Persona but a custom version of Lavender with the default `account/edit.tpl`...

**Comment by NicolasSiver** [comment]
Ah, ok. It's your initial integration of the plugin? 
I thought It's worked for you, and now It's broken.

**Comment by Radiergummi** [comment]
Sorry if I didn't make it clear. I had it working previously, yes. Actually, I installed it the day you released it, thank you again :)
It worked flawlessly as far as I know, until the users reported it didn't anymore.

**Comment by NicolasSiver** [comment]
@Radiergummi ok, I have checked with both themes: Persona `0.2.0` and Lavender/Vanilla `1.0.45`/`1.0.144`, and it works ok with both.

Here is screenshot of the Lavender:

![screen shot 2015-06-30 at 7 45 40 pm](https://cloud.githubusercontent.com/assets/135263/8436389/be761608-1f60-11e5-9066-4cfeb661a1ef.png)

**Comment by NicolasSiver** [comment]
Re-open if you still have problem ;)
