### ISSUE TITLE
The plugin makes it impossible to nodebb start

### ISSUE THREAD

**Issue by 1019-h** [NicolasSiver/nodebb-plugin-ns-custom-fields#56]
Hi !

Quick disclaimer : I'm a front-dev and I'm very bad at back-end for now so it may be my fault. I don't understand fully everything when it comes to console, error logs, etc.

I tried yesterday to install this plugin to my nodeBB forum in local but once I stop nodebb and re-start it, it just doesn't work : the "node.exe" console pops in and out 3 to 4 times before not launching anymore and when I look at the error logs, it says that the server isn't running - eventhough it is.

When I uninstall this plugin, it works just fine.

If anyone have a solution, I'd like to hear it !
Thanks !

**Comment by NicolasSiver** [comment]
@1019-h very likely Plugin is incompatible with your NodeBB version. It crashes the app, which is why the server is not running.

Version compatibility of the plugins for NodeBB - always was a challenge. I don't know if something has changed lately.

**Comment by 1019-h** [comment]
Okay, thank you !
