### ISSUE TITLE
Input fields are displayed in the breadcrumbs area in 0.9.1

### ISSUE THREAD

**Issue by Radiergummi** [NicolasSiver/nodebb-plugin-ns-custom-fields#9]
Hi Nicolas, I'm currently trying to update to 0.9.1, including your plugin.
After changing `postTools` to `posts` in `app/nodebb.js` on line 10, the plugin appears to work pretty well. When trying to edit my profile fields though, I noticed the input section is displayed in the breadcrumbs instead of the intended location in the template.

Looks like this:  
<img width="1177" alt="bildschirmfoto 2015-12-04 um 19 18 03" src="https://cloud.githubusercontent.com/assets/6115429/11597399/c99de660-9abb-11e5-8284-67555462593d.png">

The markup (where it should be):
<img width="829" alt="bildschirmfoto 2015-12-04 um 19 20 13" src="https://cloud.githubusercontent.com/assets/6115429/11597462/152d903a-9abc-11e5-910e-387ec1474759.png">

The markup (where it actually is):
<img width="672" alt="bildschirmfoto 2015-12-04 um 19 19 07" src="https://cloud.githubusercontent.com/assets/6115429/11597430/f03d46d0-9abb-11e5-9144-cfccdff4da14.png">

The template code:

````html
...
                                </a>
                                <!-- END sso -->
                        </div>
                        <!-- ENDIF sso.length -->
                </div>


                <div class="panel panel-default ns-custom-fields-panel">
                    <div class="panel-body text-center">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- BEGIN customFields -->
                                <span class="account-bio-label">{customFields.name}</span>
                                <span class="account-bio-value">{customFields.value}</span>
                                <!-- END customFields -->
                            </div>
                        </div>
                    </div>
                </div>
        </div>
</div>
...
````

**Comment by NicolasSiver** [comment]
Hi.
Current implementation is heavily coupled with themes. After 0.9.1 changes, it will not work in the same way.

Idea will be rethought, how plugin will work in `0.9.x`. Main Idea: plugin should depend less on current theme. So plugin will not interfere with theme. 
Plugin will use dedicated filter, same that is used by PushBullet plugin. UX will be _a bit_ worse, but Plugin will receive dedicated page, and ability to implement more interesting UI solutions (field validation for example)

I also need this plugin workable on 0.9.1 so stay tuned ;)
